### ISSUE TITLE
Pytanie odnośnie konstrukcji Dto

### ISSUE THREAD

**Issue by CoKrokToUpadek** [interceptor2048/projekt-jdp-2210-01#10]
Skąd taka konstrukcja? Bo w sumie nie jest oparta o encje (co ma sens), ale nie jest też oparta o cart.spec.json (dalej nie wiem czy dobrze rozumiem to łączenie z front endem). Nie trzeba nic zmieniać, proszę tylko o wyjaśnienie skąd akurat te pola w klasie.

**Comment by JoankaWolf** [comment]
znalazłam :) następnym razem odpiszę tutaj :)
